// This file is automatically generated by state-gen script
// Do not edit this file manually
#pragma once

#include <stdint.h>

#define EM_STATE_CALIBRATION 0x02
#define EM_STATE_DRVIE 0x04

typedef struct
{
  uint16_t sensor_low[16];
  uint16_t sensor_high[16];
  uint16_t sensor_raw[16];
  double sensor_data[16];
  double position;
  double speed;
  double battery_voltage;
  uint8_t track;
  uint32_t encoder_left;
  uint32_t encoder_right;
} state_t;

void state_print_offsets(state_t *state, char *buffer);
extern state_t state;
