// This file is automatically generated by state-gen script
// Do not edit this file manually
#include "state.h"

void state_print_offsets(state_t *state, char *buffer)
{
  buffer += sprintf("STATE_DEFINITION_START\n");
  uint8_t base_address = (uint8_t *)state;
  buffer += sprintf(buffer, "sensor_low: %ld\n", (uint8_t *)(&state->sensor_low) - base_address);
  buffer += sprintf(buffer, "sensor_high: %ld\n", (uint8_t *)(&state->sensor_high) - base_address);
  buffer += sprintf(buffer, "sensor_raw: %ld\n", (uint8_t *)(&state->sensor_raw) - base_address);
  buffer += sprintf(buffer, "sensor_data: %ld\n", (uint8_t *)(&state->sensor_data) - base_address);
  buffer += sprintf(buffer, "position: %ld\n", (uint8_t *)(&state->position) - base_address);
  buffer += sprintf(buffer, "speed: %ld\n", (uint8_t *)(&state->speed) - base_address);
  buffer += sprintf(buffer, "battery_voltage: %ld\n", (uint8_t *)(&state->battery_voltage) - base_address);
  buffer += sprintf(buffer, "track: %ld\n", (uint8_t *)(&state->track) - base_address);
  buffer += sprintf(buffer, "encoder_left: %ld\n", (uint8_t *)(&state->encoder_left) - base_address);
  buffer += sprintf(buffer, "encoder_right: %ld\n", (uint8_t *)(&state->encoder_right) - base_address);
  buffer += sprintf("STATE_DEFINITION_END\n");
}
