// This file is automatically generated by state-gen script
// Do not edit this file manually
#include "state.h"
#include <stdio.h>
#include <stdint.h>

void state_print_offsets(state_t *state, char *buffer)
{
  buffer += sprintf(buffer, "[");
  uint8_t* base_address = (uint8_t *)state;
  buffer += sprintf(buffer, "%lu,", (uint64_t)(&state->state - base_address));
  buffer += sprintf(buffer, "%lu,", (uint64_t)(&state->sensor_low - base_address));
  buffer += sprintf(buffer, "%lu,", (uint64_t)(&state->sensor_high - base_address));
  buffer += sprintf(buffer, "%lu,", (uint64_t)(&state->sensor_raw - base_address));
  buffer += sprintf(buffer, "%lu,", (uint64_t)(&state->sensor_data - base_address));
  buffer += sprintf(buffer, "%lu,", (uint64_t)(&state->position - base_address));
  buffer += sprintf(buffer, "%lu,", (uint64_t)(&state->speed - base_address));
  buffer += sprintf(buffer, "%lu,", (uint64_t)(&state->battery_voltage - base_address));
  buffer += sprintf(buffer, "%lu,", (uint64_t)(&state->track - base_address));
  buffer += sprintf(buffer, "%lu,", (uint64_t)(&state->encoder_left - base_address));
  buffer += sprintf(buffer, "%lu", (uint64_t)(&state->encoder_right - base_address));
  buffer += sprintf(buffer, "]");
}
