// This file is automatically generated by state-gen script
// Do not edit this file manually
#pragma once

#include <stdint.h>

#define EM_STATE_HALT 0x00
#define EM_STATE_IDLE 0x01
#define EM_STATE_CALI_HIGH 0x02
#define EM_STATE_CALI_LOW 0x04
#define EM_STATE_DRIVE 0x08
#define EM_STATE_MUSIC 0x10
#define EM_STATE_ALL (~(uint32_t)(0))

typedef struct
{
  uint32_t state;
  uint16_t sensor_low[16];
  uint16_t sensor_high[16];
  uint16_t sensor_raw[16];
  double sensor_data[16];
  double position;
  double speed;
  double battery_voltage;
  uint8_t track;
  int32_t encoder_left;
  int32_t encoder_right;
} state_t;

void state_print_offsets(state_t *state, char *buffer);
extern state_t *state;
